
const K={meta:null,recipes:[],ingredients:[],foods:[],fluids:[],prep:[],recipe:null,added:[],selectedIngredient:null,selectedSpice:null};
const $=id=>document.getElementById(id); const num=v=>Number(v)||0; const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=1)=>Number(v||0).toFixed(d).replace(/\.0$/,'');
async function loadJSON(p){const r=await fetch(p);if(!r.ok)throw new Error(`${p}: ${r.status}`);return r.json()}
Promise.all(['data/meta.json','data/evolved-recipes.json','data/ingredients.json','data/foods.json','data/fluids.json','data/preparation-recipes.json'].map(loadJSON)).then(([meta,recipes,ingredients,foods,fluids,prep])=>{Object.assign(K,{meta,recipes,ingredients,foods,fluids,prep});init()}).catch(e=>{$('dataStatus').textContent='Data load failed';$('dataStatus').style.color='#f0b18d';console.error(e)});
function init(){
 $('dataStatus').textContent=`${K.meta.counts.evolvedRecipes} evolved recipes • ${K.meta.counts.evolvedUsableItems} usable items`;
 bindTabs(); bindSnapshot(); populateFamilies(); bindFoodBrowser(); bindPrepBrowser(); renderMechanics();
 $('clearDish').onclick=()=>{K.added=[];renderFinal()}; document.addEventListener('click',()=>document.querySelectorAll('.picker.open').forEach(x=>x.classList.remove('open')));
}
function bindTabs(){document.querySelectorAll('.tab-button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab-button,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')})}
function bindSnapshot(){['weight','calories','carbs','lipids','proteins','cookingLevel'].forEach(id=>$(id).addEventListener('input',()=>{snapshot();renderSelectedPreviews();renderFinal()}));snapshot()}
function snapshot(){const w=num($('weight').value),c=num($('calories').value),ca=num($('carbs').value),f=num($('lipids').value),p=num($('proteins').value),L=clamp(num($('cookingLevel').value),0,10);const gt=1000+(w-80)*40, mm=(ca>700||f>700)?3:(ca>400||f>400)?2:1;$('weightTrend').textContent=c>gt?'Gaining':c<Math.min((w-70)*30,0)?'Losing':'Stable';$('gainThreshold').textContent=Math.round(gt);$('macroMult').textContent='×'+mm;$('proteinMult').textContent=p>50&&p<300?'×1.5':p<-300?'×0.7':'×1';$('cookNutrition').textContent='×'+(1+L/15).toFixed(3);$('sourceUse').textContent=Math.round((1-.03*L)*100)+'%'}
function populateFamilies(){const fams=[...new Set(K.recipes.map(r=>r.template))].sort((a,b)=>a.localeCompare(b));$('recipeFamily').innerHTML=fams.map(x=>`<option>${esc(x)}</option>`).join('');$('recipeFamily').onchange=populateVariants; $('recipeVariant').onchange=selectRecipe; const preferred=fams.includes('Pasta')?'Pasta':fams[0];$('recipeFamily').value=preferred;populateVariants()}
function populateVariants(){const fam=$('recipeFamily').value, rs=K.recipes.filter(r=>r.template===fam);$('recipeVariant').innerHTML=rs.map(r=>`<option value="${esc(r.id)}">${esc(r.id)} — ${esc(shortId(r.baseItem))}</option>`).join('');selectRecipe()}
function selectRecipe(){K.recipe=K.recipes.find(r=>r.id===$('recipeVariant').value)||null;K.added=[];K.selectedIngredient=null;K.selectedSpice=null;renderBase();renderPickers();renderFinal()}
function shortId(id){return String(id||'').replace(/^Base\./,'')}
function metric(label,value){return `<div class="metric"><b>${esc(value)}</b><small>${esc(label)}</small></div>`}
function renderBase(){const r=K.recipe;if(!r)return;const b=r.baseStats||{};const matches=K.prep.filter(p=>(p.produces||[]).includes(r.baseItem));let prepHTML='';if(matches.length){prepHTML=`<div class="prep-guide"><h3>How to get this base</h3>${matches.map(p=>`<div class="prep-card"><div class="prep-name">${esc(splitName(p.name))}</div><ul class="prep-inputs">${p.inputs.map(x=>`<li>${esc(prettyInput(x))}</li>`).join('')}</ul><div class="muted">Produces ${esc(shortId(r.baseItem))} • ${esc(p.source)}</div></div>`).join('')}</div>`}else{prepHTML=`<div class="prep-guide"><h3>How to get this base</h3><div class="prep-card"><div class="muted">No direct Cooking craft recipe indexed for this base. The evolved recipe starts from <b>${esc(shortId(r.baseItem))}</b> itself.</div></div></div>`}
 $('baseInfo').innerHTML=`<div class="base-grid"><div class="base-id"><small>Base item</small><b>${esc(r.baseItem)}</b></div><div class="base-id"><small>Evolved result</small><b>${esc(r.resultItem)}</b></div></div><div class="base-metrics">${metric('Calories',fmt(b.calories))}${metric('Carbs',fmt(b.carbs))}${metric('Fat',fmt(b.fat))}${metric('Protein',fmt(b.protein))}${metric('Hunger relief',fmt(Math.abs(b.hunger),0))}${metric('Max ingredients',r.maxItems)}</div><div class="cook-note">${r.minimumWater?`Requires at least <b>${fmt(r.minimumWater)} water</b> before the first evolved ingredient. `:''}${r.cookable?`The evolved result is <b>cookable</b>${r.resultStats.minutesToCook?` (${fmt(r.resultStats.minutesToCook,0)} min to cook / ${fmt(r.resultStats.minutesToBurn,0)} min to burn)` : ''}.`:'This evolved result is not marked Cookable.'} Food bases carry their starting nutrition into the result; non-food container bases start at zero.</div>${prepHTML}`}
function splitName(s){return String(s).replace(/([a-z])([A-Z])/g,'$1 $2').replace(/\d+$/,'').trim()}
function prettyInput(s){return s.replace(/^item\s+/,'').replace(/\[Base\./g,'[').replace(/Base\./g,'').replace(/tags\[base:/g,'tag[').replace(/categories\[/g,'[').replace(/\s+mode:[^\s]+/g,'').replace(/\s+flags\[[^\]]+\]/g,'').replace(/\s+mappers\[[^\]]+\]/g,'').replace(/;/g,' / ')}
function eligible(role){if(!K.recipe)return[];const t=K.recipe.template;return K.ingredients.filter(it=>it.evolved&&it.evolved[t]&&Boolean(it.spice)===(role==='spice'))}
function iconLevel(v,max){if(v<=0)return 0;return Math.min(4,Math.ceil(v/(max/4)))}
function icons(it){const m=K.meta.macroMax, groups=[['calories','macro-fire','macro-cal'],['protein','macro-protein','macro-protein'],['fat','macro-fat','macro-fat'],['carbs','macro-carb','macro-carb']];return `<span class="macro-icons">${groups.map(([k,id,cl])=>{const n=iconLevel(num(it[k]),m[k]);return n?`<span class="macro-group">${Array.from({length:n},()=>`<svg class="macro-icon ${cl}"><use href="#${id}"/></svg>`).join('')}</span>`:''}).join('')}</span>`}
function renderPickers(){const ing=eligible('ingredient'),sp=eligible('spice');$('ingredientPicker').innerHTML=pickerHTML('ingredient',ing);$('spicePicker').innerHTML=pickerHTML('spice',sp);wirePicker('ingredient',ing);wirePicker('spice',sp);$('ingredientPreview').className='item-preview empty';$('ingredientPreview').textContent=`${ing.length} eligible ingredients for ${K.recipe.template}. Select one above.`;$('spicePreview').className='item-preview empty';$('spicePreview').textContent=`${sp.length} eligible seasonings for ${K.recipe.template}. Select one above.`}
function pickerHTML(role,data){return `<div class="picker" id="${role}PickerCtl"><button class="picker-button" type="button"><span class="picker-selected"><span class="picker-name">Select ${role==='spice'?'seasoning':'ingredient'}…</span><span class="picker-icons"></span></span><span>▾</span></button><div class="picker-menu">${data.map((it,i)=>`<div class="picker-option" data-index="${i}"><span>${esc(it.name)}</span>${icons(it)}</div>`).join('')}</div></div>`}
function wirePicker(role,data){const root=$(`${role}PickerCtl`),btn=root.querySelector('.picker-button');btn.onclick=e=>{e.stopPropagation();document.querySelectorAll('.picker.open').forEach(x=>{if(x!==root)x.classList.remove('open')});root.classList.toggle('open')};root.querySelectorAll('.picker-option').forEach(o=>o.onclick=e=>{e.stopPropagation();const it=data[num(o.dataset.index)];if(role==='spice')K.selectedSpice=it;else K.selectedIngredient=it;btn.querySelector('.picker-name').textContent=it.name;btn.querySelector('.picker-icons').innerHTML=icons(it);root.classList.remove('open');renderItemPreview(role,it)})}
function renderSelectedPreviews(){if(K.selectedIngredient)renderItemPreview('ingredient',K.selectedIngredient);if(K.selectedSpice)renderItemPreview('spice',K.selectedSpice)}
function stateValues(role){const p=role==='spice'?'sp':'in';return{fresh:$(p+'Fresh')?.value||'Fresh',cook:$(p+'Cook')?.value||'Raw',frozen:$(p+'Frozen')?.value==='Yes'}}
function renderItemPreview(role,it){const p=role==='spice'?'sp':'in', target=role==='spice'?$('spicePreview'):$('ingredientPreview');const use=it.evolved[K.recipe.template];target.className='item-preview';target.innerHTML=`<div class="item-title"><b>${esc(it.name)}</b>${icons(it)}</div><div class="item-values">Full source item: ${fmt(it.calories)} cal · ${fmt(it.carbs)} carbs · ${fmt(it.fat)} fat · ${fmt(it.protein)} protein · ${fmt(Math.abs(it.hunger),0)} hunger relief • recipe use ${use.use}${use.restriction?` • requires ${esc(use.restriction)}`:''}</div><div class="state-grid"><label>Freshness<select id="${p}Fresh"><option>Fresh</option><option>Stale</option><option>Rotten</option></select></label><label>Cooking state<select id="${p}Cook"><option>Raw</option><option>Cooked</option><option>Burnt</option></select></label><label>Frozen<select id="${p}Frozen"><option>No</option><option>Yes</option></select></label></div><div id="${p}Result" class="preview-result"></div><div class="add-row"><span id="${p}Warning" class="warning"></span><button id="${p}Add" class="add-button">Add ${role==='spice'?'seasoning':'ingredient'}</button></div>`;['Fresh','Cook','Frozen'].forEach(s=>$(p+s).onchange=()=>updateItemPreview(role,it));$(p+'Add').onclick=()=>addItem(role,it);updateItemPreview(role,it)}
function runtimeHunger(it,state){let h=num(it.hunger)/100;if(state.cook==='Cooked')return h*1.3;if(state.cook==='Burnt')return Math.sign(h||-1)*Math.max(Math.abs(h)/3,.01);if(state.fresh==='Stale')return Math.sign(h||-1)*Math.max(Math.abs(h)/1.3,.01);if(state.fresh==='Rotten')return Math.sign(h||-1)*Math.max(Math.abs(h)/2.2,.01);return h}
function validate(role,it,state){const L=clamp(num($('cookingLevel').value),0,10), use=it.evolved[K.recipe.template];if(state.cook==='Burnt')return'Burnt source foods are rejected by evolved recipes.';if(state.frozen&&!K.recipe.allowFrozenItem)return'Frozen source foods are rejected by this evolved recipe.';if(state.fresh==='Rotten'&&L<7)return'Rotten ingredients require Cooking 7 or higher.';if(use.restriction==='Cooked'&&state.cook!=='Cooked')return'This item is only eligible when cooked.';if(role==='ingredient'&&K.added.filter(x=>x.role==='ingredient').length>=K.recipe.maxItems)return`This recipe already has ${K.recipe.maxItems} normal ingredients.`;if(role==='spice'&&K.added.some(x=>x.role==='spice'&&x.item.id===it.id))return'This seasoning is already in the dish; duplicate spices are blocked.';return''}
function contribution(role,it,state){const L=clamp(num($('cookingLevel').value),0,10),u=it.evolved[K.recipe.template].use;let requested=u/100;const baseH=Math.abs(num(it.hunger)/100);if(state.fresh==='Rotten'){if(L===7||L===8)requested=baseH*.05;else if(L>=9)requested=baseH*.10}const getter=Math.abs(runtimeHunger(it,state));if(getter<requested)requested=getter;const sourceUsed=role==='spice'?requested:requested*(1-.03*L);const rawHung=Math.abs(num(it.hunger)/100);const fraction=rawHung?Math.min(1,Math.abs(sourceUsed/rawHung)):0;const boost=1+L/15;return{requested,sourceUsed,fraction,calories:num(it.calories)*fraction*boost,carbs:num(it.carbs)*fraction*boost,fat:num(it.fat)*fraction*boost,protein:num(it.protein)*fraction*boost,hunger:role==='spice'?0:requested*100,unhappy:role==='spice'?-requested*200:null,boredom:role==='spice'?-requested*200:null}}
function updateItemPreview(role,it){const p=role==='spice'?'sp':'in',state=stateValues(role),err=validate(role,it,state),c=contribution(role,it,state);$(p+'Warning').textContent=err||'Ready to add.';$(p+'Warning').className='warning '+(err?'':'ok');$(p+'Add').disabled=Boolean(err);$(p+'Result').innerHTML=`<strong>Contribution if added:</strong> ${fmt(c.calories)} cal · ${fmt(c.carbs)} carbs · ${fmt(c.fat)} fat · ${fmt(c.protein)} protein${role==='ingredient'?` · ${fmt(c.hunger)} hunger relief`:` · ${fmt(c.unhappy)} unhappiness · ${fmt(c.boredom)} boredom`}<br>Source fraction used for nutrition: ${fmt(c.fraction*100)}%${role==='ingredient'?` • source use reduced by Cooking to ${fmt(c.sourceUsed*100)} hunger points`:''}.`}
function addItem(role,it){const state=stateValues(role),err=validate(role,it,state);if(err)return;const c=contribution(role,it,state);K.added.push({role,item:it,state,contribution:c});renderFinal();renderSelectedPreviews()}
function renderFinal(){if(!K.recipe)return;const b=K.recipe.baseStats||{};const t={calories:num(b.calories),carbs:num(b.carbs),fat:num(b.fat),protein:num(b.protein),hunger:Math.abs(num(b.hunger)),unhappy:num(b.unhappy),boredom:num(b.boredom)};K.added.forEach(x=>{for(const k of ['calories','carbs','fat','protein','hunger'])t[k]+=num(x.contribution[k]);if(x.contribution.unhappy!=null)t.unhappy+=num(x.contribution.unhappy);if(x.contribution.boredom!=null)t.boredom+=num(x.contribution.boredom)});const normals=K.added.filter(x=>x.role==='ingredient').length,spices=K.added.filter(x=>x.role==='spice').length;$('finalDish').innerHTML=`<div class="final-title">${esc(K.recipe.displayName)}</div><div class="final-sub">${esc(K.recipe.resultItem)} • ${normals}/${K.recipe.maxItems} ingredient slots • ${spices} seasoning${spices===1?'':'s'}</div><div class="final-metrics">${metric('Calories',fmt(t.calories))}${metric('Carbs',fmt(t.carbs))}${metric('Fat',fmt(t.fat))}${metric('Protein',fmt(t.protein))}${metric('Hunger relief',fmt(t.hunger))}${metric('Cooking XP',fmt(K.added.length*3,0))}</div><div class="base-contribution"><strong>Base contribution:</strong> ${esc(shortId(K.recipe.baseItem))} starts this dish at ${fmt(b.calories)} cal / ${fmt(b.carbs)} carbs / ${fmt(b.fat)} fat / ${fmt(b.protein)} protein / ${fmt(Math.abs(b.hunger),0)} hunger relief.</div>${K.added.length?`<div class="added-list">${K.added.map((x,i)=>`<div class="added-item"><div><b>${esc(x.item.name)}</b> <span class="role-pill">${x.role}</span><div class="added-meta">${esc(x.state.fresh)} • ${esc(x.state.cook)}${x.state.frozen?' • Frozen':''}</div></div><div class="added-values">+${fmt(x.contribution.calories)} cal • +${fmt(x.contribution.carbs)} C • +${fmt(x.contribution.fat)} F • +${fmt(x.contribution.protein)} P${x.role==='ingredient'?` • +${fmt(x.contribution.hunger)} hunger`:''}<button class="remove-item" data-i="${i}" title="Remove">×</button></div></div>`).join('')}</div>`:'<div class="base-contribution">No evolved ingredients added yet. These totals are the recipe base itself, not an empty zero-stat placeholder.</div>'}<div class="cook-note">${K.recipe.cookable?'After assembly, this result is marked <b>cookable</b>. Cooking/burning the completed dish is a later state of the final food and is intentionally separate from each source ingredient\'s state.':'This recipe result is not marked Cookable in the evolved recipe definition.'}</div>`;document.querySelectorAll('.remove-item').forEach(bu=>bu.onclick=()=>{K.added.splice(num(bu.dataset.i),1);renderFinal();renderSelectedPreviews()})}
function bindFoodBrowser(){$('foodSearch').oninput=renderFoods;renderFoods()}
function rangeValue(x,key,absolute=false){const r=x.nutritionRange&&x.nutritionRange[key];if(!r)return fmt(absolute?Math.abs(num(x[key])):num(x[key]));let a=absolute?Math.abs(num(r.min)):num(r.min),b=absolute?Math.abs(num(r.max)):num(r.max);if(absolute&&a>b)[a,b]=[b,a];return Math.abs(a-b)<1e-9?fmt(a):`${fmt(a)}–${fmt(b)}`}
function foodSearchText(x){return [x.name,x.id,x.fluidName,x.nutritionNote,(x.categories||[]).join(' ')].join(' ').toLowerCase()}
function renderFoods(){const q=$('foodSearch').value.trim().toLowerCase(),all=[...K.foods,...K.fluids],matches=all.filter(x=>!q||foodSearchText(x).includes(q)),rows=matches.slice(0,300);$('foodRows').innerHTML=rows.map(x=>`<tr><td><b>${esc(x.name)}</b><br><small>${esc(x.id)}</small>${x.nutritionNote?`<br><small>${esc(x.nutritionNote)}</small>`:''}</td><td>${rangeValue(x,'calories')}</td><td>${rangeValue(x,'carbs')}</td><td>${rangeValue(x,'fat')}</td><td>${rangeValue(x,'protein')}</td><td>${rangeValue(x,'hunger',true)}</td><td>${rangeValue(x,'thirst',true)}</td><td>${x.kind==='fluid'?'—':(x.daysFresh||'—')}</td><td>${x.kind==='fluid'?'—':(x.daysRotten||'—')}</td></tr>`).join('');$('foodCount').textContent=`Showing ${rows.length} of ${matches.length} matches (${K.foods.length} item records + ${K.fluids.length} fluids normalized to 1 L).`} 
function bindPrepBrowser(){$('prepSearch').oninput=renderPrep;renderPrep()}
function renderPrep(){const q=$('prepSearch').value.trim().toLowerCase();const rows=K.prep.filter(x=>!q||x.name.toLowerCase().includes(q)||x.raw.toLowerCase().includes(q)).slice(0,200);$('prepRows').innerHTML=rows.map(x=>`<div class="recipe-row"><b>${esc(splitName(x.name))}</b><small>${x.inputs.map(prettyInput).map(esc).join(' • ')}</small>${x.produces.length?`<small>Produces: ${x.produces.map(shortId).map(esc).join(', ')}</small>`:''}<small>Source: ${esc(x.source)}</small></div>`).join('')}
function renderMechanics(){$('mechanicsRows').innerHTML=Object.entries(K.meta.mechanics).map(([k,v])=>`<div class="mechanic-card"><b>${esc(k)}</b><p>${esc(v)}</p></div>`).join('')}
